apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  creationTimestamp: '2023-07-12T11:18:59Z'
  generation: 3
  labels:
    bcdr-candidate: t
    component-name: appconnect
  managedFields:
    - apiVersion: appconnect.ibm.com/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:bcdr-candidate': {}
            'f:component-name': {}
        'f:spec':
          .: {}
          'f:contents': {}
          'f:type': {}
          'f:version': {}
      manager: unknown
      operation: Update
      time: '2023-07-12T15:03:15Z'
  name: mq-activitylog-policy
  namespace: cp4i
  resourceVersion: '8053986'
  uid: 58dd3e18-1f5d-45fb-98a0-191b091e4994
spec:
  contents: >-
    UEsDBBQAAAAAAPJW7FYAAAAAAAAAAAAAAAAQACAAbXlQb2xpY3lQcm9qZWN0L1VUDQAH6b6uZOe/rmTpvq5kdXgLAAEE6AMAAAToAwAAUEsDBBQACAAIAGo77FYAAAAAAAAAAEUCAAAnACAAbXlQb2xpY3lQcm9qZWN0L015QWN0aXZpdHlMb2cucG9saWN5eG1sVVQNAAcYjq5kPY6uZBiOrmR1eAsAAQToAwAABOgDAABtUctugzAQvFfqPyDfGzdVK/VAHKEqVJFCkAL5AIcsyKqxETYR9Ou75tGQKCd7dmbW6x1/3ZbSu0BthFYrslwsiQcq02ehihU5puHLJ/GM5erMpVawIh0YsmbPT36lpcgEGLx73oA6bzjSrkJlkFlxEbbb6YKMxJ6XSETdnOr92AHkz5dWCpDSyjCf3hWuMnSxnEsDvcahiVP8JOHM0sNxg9yIJrKFrHGtvmvdVKGQFmr3yqPyaMmFBDcyo7asKB+HlrpY2Nb69J++yoee+W0XXZfcbpSt3bbCYJfgcLfFUVnyNiggEvjbV5/O0JXHASERvxCd2NtHr5lVJplQCWCkbsF4Srbdh/EhCtJtvA92aLrnR59qyhPUcY4bNezdpze4T5kOMbr46Sz/P1BLBwhM6h3nKwEAAEUCAABQSwMEFAAIAAgA8WzqVgAAAAAAAAAAHwIAABgAIABteVBvbGljeVByb2plY3QvLnByb2plY3RVVA0AB1ZCrGQ9jq5kno2uZHV4CwABBOgDAAAE6AMAAK2RywrCMBRE1wr+Q+neRHcuYgsqLkVQP6BNrxLJoySp6N+bl5YiuBB3dyaTuYeElHfBsxtow5Rc5nM0yzOQVDVMXpb56bidLvKymIxJq9UVqN2AoZq11qWdOyKyElCIx15xRh/7mCE4uP6YKiFA2oLg1+Td1GWCwANVd4w3hxaoV0mu3dVKNsFJG10bYrVAYJXiBomzRW1AQB1D4RJoFKFWUfVQrqPSl87TmKTx0CD4Y+9vJHGq/0GQnNfTuOW205DSUXxn2YWMhwjZUNmXvL9h+MFPUEsHCMZvrO/UAAAAHwIAAFBLAwQUAAgACADxbOpWAAAAAAAAAAD4AAAAIQAgAG15UG9saWN5UHJvamVjdC9wb2xpY3kuZGVzY3JpcHRvclVUDQAHVkKsZD2OrmSeja5kdXgLAAEE6AMAAAToAwAAjY5BCsIwEEX3gncIszdRV1KadiOuXegB2nSqkSRTMoPY2xsRBDfi/r/3X90+YlB3zOwpWdjoNShMjgafLhbOp8NqB4qlS0MXKKGFGRnaZrmoE2+riYJ38zHTDZ3skV32k1BWxZnYwlVkqoxxFLXvo0YhCqzjKHr4bHXfMcKbqIrzT+rrGUqPUnXGEXOJRzavQPOjsHkCUEsHCC7DG/yWAAAA+AAAAFBLAwQUAAgACADyVuxWAAAAAAAAAADqAgAAJAAgAG15UG9saWN5UHJvamVjdC9NUUVuZHBvaW50LnBvbGljeXhtbFVUDQAH6b6uZOm+rmTpvq5kdXgLAAEE6AMAAAToAwAAfVLPb4IwFL4v2f9AuGNn4mGHijHMZWaKIrh7LU9tVkppi5n//QrWrHNmp77vx3vtgw9PvioenEBpVotxOBw8hQEIWpdMHMbhtniNnsNJ/PiAZc0ZZaBtHQQXdA4uR3GWMA6X2UyUsmbChI5PSXWXL6CSnJjfWj/XTqa1EECNfU2cLOaztMDIo5ypBG2YIB2VtdDCkghyANVdGGfbefKeF9ON7fzP50Y1Hv9WayM6rWkZ/dSGKBM1VcR2VVQ1AypHbKBPFKO7PW4eZ9qAALWulUnbagcqHo6GI4zuCNeVj8QuyPtXTZNZ/rFJVmlq9/Z4Z02Sl2KreIzRtXKCBtoqZs7zEoSxp3X8oZy11ZDni3hPuAaMHHKaLdfgPhBGPvoxJEweQeUS6MXiYc8EyrA9o/Y3L8gOuLPesq5hmU2l5O5WDzhZgYvASvYpKGFPWm4wuhX6bKJLyrrQIi+131BLBwjHu227XQEAAOoCAABQSwECFAMUAAAAAADyVuxWAAAAAAAAAAAAAAAAEAAgAAAAAAAAAAAA7UEAAAAAbXlQb2xpY3lQcm9qZWN0L1VUDQAH6b6uZOe/rmTpvq5kdXgLAAEE6AMAAAToAwAAUEsBAhQDFAAIAAgAajvsVkzqHecrAQAARQIAACcAIAAAAAAAAAAAAKSBTgAAAG15UG9saWN5UHJvamVjdC9NeUFjdGl2aXR5TG9nLnBvbGljeXhtbFVUDQAHGI6uZD2OrmQYjq5kdXgLAAEE6AMAAAToAwAAUEsBAhQDFAAIAAgA8WzqVsZvrO/UAAAAHwIAABgAIAAAAAAAAAAAAKSB7gEAAG15UG9saWN5UHJvamVjdC8ucHJvamVjdFVUDQAHVkKsZD2OrmSeja5kdXgLAAEE6AMAAAToAwAAUEsBAhQDFAAIAAgA8WzqVi7DG/yWAAAA+AAAACEAIAAAAAAAAAAAAKSBKAMAAG15UG9saWN5UHJvamVjdC9wb2xpY3kuZGVzY3JpcHRvclVUDQAHVkKsZD2OrmSeja5kdXgLAAEE6AMAAAToAwAAUEsBAhQDFAAIAAgA8lbsVse7bbtdAQAA6gIAACQAIAAAAAAAAAAAAKSBLQQAAG15UG9saWN5UHJvamVjdC9NUUVuZHBvaW50LnBvbGljeXhtbFVUDQAH6b6uZOm+rmTpvq5kdXgLAAEE6AMAAAToAwAAUEsFBgAAAAAFAAUAGgIAAPwFAAAAAA==
  type: policyproject
  version: 12.0.8.0-r3
